[package]
name = "Dimport"
version = "2025.7.15"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
walkdir = "2.5.0"
